Спринт 10 , ветка add-friends-likes
DmitriyKrasnikov/java-filmorate pull request #4
Opened 2023-03-17 13:14 UTC by DmitriyKrasnikov

2023-03-18 20:42 UTC, TarasovSam requested changes
Дмитрий, привет!
Проверил твое задание, все довольно хорошо. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilmById(filmId);
А почему для некоторых эндпоинтов ты используешь filmStorage, а для других serviceManager?
Для пользователя тоже самое.

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
Для id у тебя в коде в некоторых местах не хватает проверки на null для этого поля. Это можно решить, прописав аннотацию)
Тоже самое и для User.

И почему решил не вводить поле рейтинг фильма?)

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.debug("Попытка взаимодействовать с несуществующим фильмом {}", filmId);
Может стоит перенести логирование в одно место, чтобы было сразу понятно какие действия будут прописаны в лог?
И почему логируешь только ошибки, а удачные действия нет?

Для пользователя тоже самое.

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
А есть смысл в двух проверках?

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void addFilm(Film film) throws ValidationException {
Может же быть случай, когда film==null, что тогда будет?
И в методе update тоже самое.

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.get(id);
Почему здесь и при возвращении всех фильмов нет логирования?

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void updateUser(User user) throws UserNotFoundException {
Может же быть случай, когда user==null, что тогда будет?
И в методе add тоже самое.

2023-03-18 20:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            return users.get(id);
Почему здесь и при возвращении всех пользователей нет логирования?

2023-03-19 13:46 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Добавил

2023-03-19 13:53 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilmById(filmId);
Это мои догадки, поэтому хотел бы услышать твой комментарий.
Догадки в следующем:
Чтобы не создавать дополнительных переменных и не занимать место в памяти. 
Переменные storage добавил для улучшения читаемости кода, потому что без них любой вызов методов storage выглядел бы так : serviseManager.getService().getFilmStorage().(метод). Созданием переменной я сократил до filmStorage().(метод). В некоторых эндпоинтах не требуется обращаться к хранилищу, только к методам сервера. Поэтому обращение к методу выглядит короче. Поэтому , чтобы не увеличивать расходы памяти, я решил не создавать переменную film Servise

2023-03-19 13:55 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
Рейтинг пока что не было в тз. Может будет дальше. Аннотацию к id добавил

2023-03-19 13:58 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.debug("Попытка взаимодействовать с несуществующим фильмом {}", filmId);
Удачные действия не логирую потому, что в теории было написано, что обычно логируются только ошибки , чтобы не засорять журнал. Логирование удачных действий я добавлю, но имеет ли смысл уже в реальных проектах. Или от проекта зависит ?

2023-03-19 14:04 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.debug("Попытка взаимодействовать с несуществующим фильмом {}", filmId);
И немного не понял, что именно имеется в виду перенести в одно место. Если у меня будет логирование удачных действий , их записать, к примеру в контроллер, а неудачные собрать в один класс?

2023-03-19 15:13 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Оставил одну

2023-03-19 15:13 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void addFilm(Film film) throws ValidationException {
Добавил проверку

2023-03-19 15:13 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.get(id);
Про логирование спросил выше

2023-03-19 15:13 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            return users.get(id);
Про логирование спросил выше

2023-03-19 15:14 UTC, DmitriyKrasnikov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void updateUser(User user) throws UserNotFoundException {
Добавил проверку

2023-03-19 17:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Надеюсь, что isBlank))

2023-03-19 17:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.debug("Попытка взаимодействовать с несуществующим фильмом {}", filmId);
Да, все зависит от проекта. Где-то логируются только возникающие ошибки, где-то все действия (по ним потом идет анализ, чтобы улучшить приложение).

Ага, получается, что в контроллере в каждом эндпоинте идет логирование удачных действий, а не удачных - там, где идет проверка и обработка.

2023-03-19 17:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
Ввод поля рейтинга - довольно удобно, как по мне. Да, по ТЗ не было, так что можешь не делать)

2023-03-19 17:04 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilmById(filmId);
Это был намек на то, что в сервисе должны быть методы create, get, update, delete, getAll с вызовами соответствующих методов Storage.

2023-03-20 19:23 UTC, TarasovSam reviewed
Дмитрий, спасибо за то, что вносишь корректировки по рекомендациям, и за твои ответы. Оставил еще несколько комментариев (в основном мелкие корректировки и чуть рассуждений).
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-20 19:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.debug("Получен статус Not found");
Отлично, спасибо! Для полноты картины сообщение можно дополнить "Получен статус 404 - Not found" (для остальных тоже самое).

2023-03-20 19:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException("Передан пустой объект");
Во втором условии логирование прописал, а тут нет) Добавь его, пожалуйста.

2023-03-20 19:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException("Передан пустой объект");
Здесь тоже.

2023-03-20 19:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>  public interface FilmStorage {
Методы для FilmStorage и UserStorage идентичны, поэтому можно их выделить в интерфейс с использованием дженериков (если будет желание).
Тоже самое можно сделать и для InMemoryStorage)

2023-04-17 12:23 UTC, merged